<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('currencies')->insert([

  [
    "id"=> 1,
    "country_id"=> 1,
    "name"=> "Afghan Afghani",
    "code"=> "AFN",
    "precision"=> 0,
    "symbol"=> "Af",
    "symbol_native"=> "؋",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 2,
    "country_id"=> 2,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 3,
    "country_id"=> 3,
    "name"=> "Albanian Lek",
    "code"=> "ALL",
    "precision"=> 0,
    "symbol"=> "ALL",
    "symbol_native"=> "Lek",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 4,
    "country_id"=> 4,
    "name"=> "Algerian Dinar",
    "code"=> "DZD",
    "precision"=> 2,
    "symbol"=> "DA",
    "symbol_native"=> "د.ج.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 5,
    "country_id"=> 5,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 6,
    "country_id"=> 6,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 7,
    "country_id"=> 7,
    "name"=> "AOA",
    "code"=> "AOA",
    "precision"=> 2,
    "symbol"=> "Kz",
    "symbol_native"=> "Kz",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 8,
    "country_id"=> 8,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 9,
    "country_id"=> 9,
    "name"=> "AAD",
    "code"=> "AAD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 10,
    "country_id"=> 10,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 11,
    "country_id"=> 11,
    "name"=> "Argentine Peso",
    "code"=> "ARS",
    "precision"=> 2,
    "symbol"=> "AR$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 12,
    "country_id"=> 12,
    "name"=> "Armenian Dram",
    "code"=> "AMD",
    "precision"=> 0,
    "symbol"=> "AMD",
    "symbol_native"=> "դր.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 13,
    "country_id"=> 13,
    "name"=> "AWG",
    "code"=> "AWG",
    "precision"=> 2,
    "symbol"=> "ƒ",
    "symbol_native"=> "ƒ",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 14,
    "country_id"=> 14,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 15,
    "country_id"=> 15,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 16,
    "country_id"=> 16,
    "name"=> "Azerbaijani Manat",
    "code"=> "AZN",
    "precision"=> 2,
    "symbol"=> "man.",
    "symbol_native"=> "ман.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 17,
    "country_id"=> 17,
    "name"=> "Bahraini Dinar",
    "code"=> "BHD",
    "precision"=> 3,
    "symbol"=> "BD",
    "symbol_native"=> "د.ب.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 18,
    "country_id"=> 18,
    "name"=> "Bangladeshi Taka",
    "code"=> "BDT",
    "precision"=> 2,
    "symbol"=> "Tk",
    "symbol_native"=> "৳",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 19,
    "country_id"=> 19,
    "name"=> "BBD",
    "code"=> "BBD",
    "precision"=> 2,
    "symbol"=> "Bds$",
    "symbol_native"=> "Bds$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 20,
    "country_id"=> 20,
    "name"=> "Belarusian Ruble",
    "code"=> "BYN",
    "precision"=> 2,
    "symbol"=> "Br",
    "symbol_native"=> "руб.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 21,
    "country_id"=> 21,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 22,
    "country_id"=> 22,
    "name"=> "Belize Dollar",
    "code"=> "BZD",
    "precision"=> 2,
    "symbol"=> "BZ$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 23,
    "country_id"=> 23,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 24,
    "country_id"=> 24,
    "name"=> "BMD",
    "code"=> "BMD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 25,
    "country_id"=> 25,
    "name"=> "BTN",
    "code"=> "BTN",
    "precision"=> 2,
    "symbol"=> "Nu.",
    "symbol_native"=> "Nu.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 26,
    "country_id"=> 26,
    "name"=> "Bolivian Boliviano",
    "code"=> "BOB",
    "precision"=> 2,
    "symbol"=> "Bs",
    "symbol_native"=> "Bs",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 27,
    "country_id"=> 27,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 28,
    "country_id"=> 28,
    "name"=> "Bosnia-Herzegovina Convertible Mark",
    "code"=> "BAM",
    "precision"=> 2,
    "symbol"=> "KM",
    "symbol_native"=> "KM",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 29,
    "country_id"=> 29,
    "name"=> "Botswanan Pula",
    "code"=> "BWP",
    "precision"=> 2,
    "symbol"=> "BWP",
    "symbol_native"=> "P",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 30,
    "country_id"=> 30,
    "name"=> "Norwegian Krone",
    "code"=> "NOK",
    "precision"=> 2,
    "symbol"=> "Nkr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 31,
    "country_id"=> 31,
    "name"=> "Brazilian Real",
    "code"=> "BRL",
    "precision"=> 2,
    "symbol"=> "R$",
    "symbol_native"=> "R$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 32,
    "country_id"=> 32,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 33,
    "country_id"=> 33,
    "name"=> "Brunei Dollar",
    "code"=> "BND",
    "precision"=> 2,
    "symbol"=> "BN$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 34,
    "country_id"=> 34,
    "name"=> "Bulgarian Lev",
    "code"=> "BGN",
    "precision"=> 2,
    "symbol"=> "BGN",
    "symbol_native"=> "лв.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 35,
    "country_id"=> 35,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 36,
    "country_id"=> 36,
    "name"=> "Burundian Franc",
    "code"=> "BIF",
    "precision"=> 0,
    "symbol"=> "FBu",
    "symbol_native"=> "FBu",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 37,
    "country_id"=> 37,
    "name"=> "Cambodian Riel",
    "code"=> "KHR",
    "precision"=> 2,
    "symbol"=> "KHR",
    "symbol_native"=> "៛",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 38,
    "country_id"=> 38,
    "name"=> "CFA Franc BEAC",
    "code"=> "XAF",
    "precision"=> 0,
    "symbol"=> "FCFA",
    "symbol_native"=> "FCFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 39,
    "country_id"=> 39,
    "name"=> "Canadian Dollar",
    "code"=> "CAD",
    "precision"=> 2,
    "symbol"=> "CA$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 40,
    "country_id"=> 40,
    "name"=> "Cape Verdean Escudo",
    "code"=> "CVE",
    "precision"=> 2,
    "symbol"=> "CV$",
    "symbol_native"=> "CV$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 41,
    "country_id"=> 41,
    "name"=> "KYD",
    "code"=> "KYD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 42,
    "country_id"=> 42,
    "name"=> "CFA Franc BEAC",
    "code"=> "XAF",
    "precision"=> 0,
    "symbol"=> "FCFA",
    "symbol_native"=> "FCFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 43,
    "country_id"=> 43,
    "name"=> "CFA Franc BEAC",
    "code"=> "XAF",
    "precision"=> 0,
    "symbol"=> "FCFA",
    "symbol_native"=> "FCFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 44,
    "country_id"=> 44,
    "name"=> "Chilean Peso",
    "code"=> "CLP",
    "precision"=> 0,
    "symbol"=> "CL$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 45,
    "country_id"=> 45,
    "name"=> "Chinese Yuan",
    "code"=> "CNY",
    "precision"=> 2,
    "symbol"=> "CN¥",
    "symbol_native"=> "CN¥",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 46,
    "country_id"=> 46,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 47,
    "country_id"=> 47,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 48,
    "country_id"=> 48,
    "name"=> "Colombian Peso",
    "code"=> "COP",
    "precision"=> 0,
    "symbol"=> "CO$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 49,
    "country_id"=> 49,
    "name"=> "Comorian Franc",
    "code"=> "KMF",
    "precision"=> 0,
    "symbol"=> "CF",
    "symbol_native"=> "FC",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 50,
    "country_id"=> 50,
    "name"=> "CFA Franc BEAC",
    "code"=> "XAF",
    "precision"=> 0,
    "symbol"=> "FCFA",
    "symbol_native"=> "FCFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 51,
    "country_id"=> 51,
    "name"=> "New Zealand Dollar",
    "code"=> "NZD",
    "precision"=> 2,
    "symbol"=> "NZ$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 52,
    "country_id"=> 52,
    "name"=> "Costa Rican Colón",
    "code"=> "CRC",
    "precision"=> 0,
    "symbol"=> "₡",
    "symbol_native"=> "₡",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 53,
    "country_id"=> 53,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 54,
    "country_id"=> 54,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 55,
    "country_id"=> 55,
    "name"=> "CUP",
    "code"=> "CUP",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 56,
    "country_id"=> 56,
    "name"=> "ANG",
    "code"=> "ANG",
    "precision"=> 2,
    "symbol"=> "ƒ",
    "symbol_native"=> "ƒ",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 57,
    "country_id"=> 57,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 58,
    "country_id"=> 58,
    "name"=> "Czech Republic Koruna",
    "code"=> "CZK",
    "precision"=> 2,
    "symbol"=> "Kč",
    "symbol_native"=> "Kč",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 59,
    "country_id"=> 59,
    "name"=> "Congolese Franc",
    "code"=> "CDF",
    "precision"=> 2,
    "symbol"=> "CDF",
    "symbol_native"=> "FrCD",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 60,
    "country_id"=> 60,
    "name"=> "Danish Krone",
    "code"=> "DKK",
    "precision"=> 2,
    "symbol"=> "Dkr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 61,
    "country_id"=> 61,
    "name"=> "Djiboutian Franc",
    "code"=> "DJF",
    "precision"=> 0,
    "symbol"=> "Fdj",
    "symbol_native"=> "Fdj",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 62,
    "country_id"=> 62,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 63,
    "country_id"=> 63,
    "name"=> "Dominican Peso",
    "code"=> "DOP",
    "precision"=> 2,
    "symbol"=> "RD$",
    "symbol_native"=> "RD$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 64,
    "country_id"=> 64,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 65,
    "country_id"=> 65,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 66,
    "country_id"=> 66,
    "name"=> "Egyptian Pound",
    "code"=> "EGP",
    "precision"=> 2,
    "symbol"=> "EGP",
    "symbol_native"=> "ج.م.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 67,
    "country_id"=> 67,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 68,
    "country_id"=> 68,
    "name"=> "CFA Franc BEAC",
    "code"=> "XAF",
    "precision"=> 0,
    "symbol"=> "FCFA",
    "symbol_native"=> "FCFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 69,
    "country_id"=> 69,
    "name"=> "Eritrean Nakfa",
    "code"=> "ERN",
    "precision"=> 2,
    "symbol"=> "Nfk",
    "symbol_native"=> "Nfk",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 70,
    "country_id"=> 70,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 71,
    "country_id"=> 71,
    "name"=> "Ethiopian Birr",
    "code"=> "ETB",
    "precision"=> 2,
    "symbol"=> "Br",
    "symbol_native"=> "Br",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 72,
    "country_id"=> 72,
    "name"=> "FKP",
    "code"=> "FKP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 73,
    "country_id"=> 73,
    "name"=> "Danish Krone",
    "code"=> "DKK",
    "precision"=> 2,
    "symbol"=> "Dkr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 74,
    "country_id"=> 74,
    "name"=> "FJD",
    "code"=> "FJD",
    "precision"=> 2,
    "symbol"=> "FJ$",
    "symbol_native"=> "FJ$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 75,
    "country_id"=> 75,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 76,
    "country_id"=> 76,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 77,
    "country_id"=> 77,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 78,
    "country_id"=> 78,
    "name"=> "XPF",
    "code"=> "XPF",
    "precision"=> 2,
    "symbol"=> "₣",
    "symbol_native"=> "₣",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 79,
    "country_id"=> 79,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 80,
    "country_id"=> 80,
    "name"=> "CFA Franc BEAC",
    "code"=> "XAF",
    "precision"=> 0,
    "symbol"=> "FCFA",
    "symbol_native"=> "FCFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 81,
    "country_id"=> 81,
    "name"=> "GMD",
    "code"=> "GMD",
    "precision"=> 2,
    "symbol"=> "D",
    "symbol_native"=> "D",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 82,
    "country_id"=> 82,
    "name"=> "Georgian Lari",
    "code"=> "GEL",
    "precision"=> 2,
    "symbol"=> "GEL",
    "symbol_native"=> "GEL",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 83,
    "country_id"=> 83,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 84,
    "country_id"=> 84,
    "name"=> "Ghanaian Cedi",
    "code"=> "GHS",
    "precision"=> 2,
    "symbol"=> "GH₵",
    "symbol_native"=> "GH₵",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 85,
    "country_id"=> 85,
    "name"=> "GIP",
    "code"=> "GIP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 86,
    "country_id"=> 86,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 87,
    "country_id"=> 87,
    "name"=> "Danish Krone",
    "code"=> "DKK",
    "precision"=> 2,
    "symbol"=> "Dkr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 88,
    "country_id"=> 88,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 89,
    "country_id"=> 89,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 90,
    "country_id"=> 90,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 91,
    "country_id"=> 91,
    "name"=> "Guatemalan Quetzal",
    "code"=> "GTQ",
    "precision"=> 2,
    "symbol"=> "GTQ",
    "symbol_native"=> "Q",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 92,
    "country_id"=> 92,
    "name"=> "British Pound Sterling",
    "code"=> "GBP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 93,
    "country_id"=> 93,
    "name"=> "Guinean Franc",
    "code"=> "GNF",
    "precision"=> 0,
    "symbol"=> "FG",
    "symbol_native"=> "FG",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 94,
    "country_id"=> 94,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 95,
    "country_id"=> 95,
    "name"=> "GYD",
    "code"=> "GYD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 96,
    "country_id"=> 96,
    "name"=> "HTG",
    "code"=> "HTG",
    "precision"=> 2,
    "symbol"=> "G",
    "symbol_native"=> "G",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 97,
    "country_id"=> 97,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 98,
    "country_id"=> 98,
    "name"=> "Honduran Lempira",
    "code"=> "HNL",
    "precision"=> 2,
    "symbol"=> "HNL",
    "symbol_native"=> "L",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 99,
    "country_id"=> 99,
    "name"=> "Hong Kong Dollar",
    "code"=> "HKD",
    "precision"=> 2,
    "symbol"=> "HK$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 100,
    "country_id"=> 100,
    "name"=> "Hungarian Forint",
    "code"=> "HUF",
    "precision"=> 0,
    "symbol"=> "Ft",
    "symbol_native"=> "Ft",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 101,
    "country_id"=> 101,
    "name"=> "Icelandic Króna",
    "code"=> "ISK",
    "precision"=> 0,
    "symbol"=> "Ikr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 102,
    "country_id"=> 102,
    "name"=> "Indian Rupee",
    "code"=> "INR",
    "precision"=> 2,
    "symbol"=> "Rs",
    "symbol_native"=> "টকা",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 103,
    "country_id"=> 103,
    "name"=> "Indonesian Rupiah",
    "code"=> "IDR",
    "precision"=> 0,
    "symbol"=> "Rp",
    "symbol_native"=> "Rp",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 104,
    "country_id"=> 104,
    "name"=> "Iranian Rial",
    "code"=> "IRR",
    "precision"=> 0,
    "symbol"=> "IRR",
    "symbol_native"=> "﷼",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 105,
    "country_id"=> 105,
    "name"=> "Iraqi Dinar",
    "code"=> "IQD",
    "precision"=> 0,
    "symbol"=> "IQD",
    "symbol_native"=> "د.ع.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 106,
    "country_id"=> 106,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 107,
    "country_id"=> 107,
    "name"=> "Israeli New Sheqel",
    "code"=> "ILS",
    "precision"=> 2,
    "symbol"=> "₪",
    "symbol_native"=> "₪",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 108,
    "country_id"=> 108,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 109,
    "country_id"=> 109,
    "name"=> "Jamaican Dollar",
    "code"=> "JMD",
    "precision"=> 2,
    "symbol"=> "J$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 110,
    "country_id"=> 110,
    "name"=> "Japanese Yen",
    "code"=> "JPY",
    "precision"=> 0,
    "symbol"=> "¥",
    "symbol_native"=> "￥",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 111,
    "country_id"=> 111,
    "name"=> "British Pound Sterling",
    "code"=> "GBP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 112,
    "country_id"=> 112,
    "name"=> "Jordanian Dinar",
    "code"=> "JOD",
    "precision"=> 3,
    "symbol"=> "JD",
    "symbol_native"=> "د.أ.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 113,
    "country_id"=> 113,
    "name"=> "Kazakhstani Tenge",
    "code"=> "KZT",
    "precision"=> 2,
    "symbol"=> "KZT",
    "symbol_native"=> "тңг.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 114,
    "country_id"=> 114,
    "name"=> "Kenyan Shilling",
    "code"=> "KES",
    "precision"=> 2,
    "symbol"=> "Ksh",
    "symbol_native"=> "Ksh",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 115,
    "country_id"=> 115,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 116,
    "country_id"=> 116,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 117,
    "country_id"=> 117,
    "name"=> "Kuwaiti Dinar",
    "code"=> "KWD",
    "precision"=> 3,
    "symbol"=> "KD",
    "symbol_native"=> "د.ك.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 118,
    "country_id"=> 118,
    "name"=> "KGS",
    "code"=> "KGS",
    "precision"=> 2,
    "symbol"=> "лв",
    "symbol_native"=> "лв",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 119,
    "country_id"=> 119,
    "name"=> "LAK",
    "code"=> "LAK",
    "precision"=> 2,
    "symbol"=> "₭",
    "symbol_native"=> "₭",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 120,
    "country_id"=> 120,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 121,
    "country_id"=> 121,
    "name"=> "Lebanese Pound",
    "code"=> "LBP",
    "precision"=> 0,
    "symbol"=> "L.L.",
    "symbol_native"=> "ل.ل.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 122,
    "country_id"=> 122,
    "name"=> "LSL",
    "code"=> "LSL",
    "precision"=> 2,
    "symbol"=> "L",
    "symbol_native"=> "L",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 123,
    "country_id"=> 123,
    "name"=> "LRD",
    "code"=> "LRD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 124,
    "country_id"=> 124,
    "name"=> "Libyan Dinar",
    "code"=> "LYD",
    "precision"=> 3,
    "symbol"=> "LD",
    "symbol_native"=> "د.ل.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 125,
    "country_id"=> 125,
    "name"=> "Swiss Franc",
    "code"=> "CHF",
    "precision"=> 2,
    "symbol"=> "CHF",
    "symbol_native"=> "CHF",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 126,
    "country_id"=> 126,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 127,
    "country_id"=> 127,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 128,
    "country_id"=> 128,
    "name"=> "Macanese Pataca",
    "code"=> "MOP",
    "precision"=> 2,
    "symbol"=> "MOP$",
    "symbol_native"=> "MOP$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 129,
    "country_id"=> 129,
    "name"=> "Macedonian Denar",
    "code"=> "MKD",
    "precision"=> 2,
    "symbol"=> "MKD",
    "symbol_native"=> "MKD",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 130,
    "country_id"=> 130,
    "name"=> "Malagasy Ariary",
    "code"=> "MGA",
    "precision"=> 0,
    "symbol"=> "MGA",
    "symbol_native"=> "MGA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 131,
    "country_id"=> 131,
    "name"=> "MWK",
    "code"=> "MWK",
    "precision"=> 2,
    "symbol"=> "MK",
    "symbol_native"=> "MK",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 132,
    "country_id"=> 132,
    "name"=> "Malaysian Ringgit",
    "code"=> "MYR",
    "precision"=> 2,
    "symbol"=> "RM",
    "symbol_native"=> "RM",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 133,
    "country_id"=> 133,
    "name"=> "MVR",
    "code"=> "MVR",
    "precision"=> 2,
    "symbol"=> "Rf",
    "symbol_native"=> "Rf",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 134,
    "country_id"=> 134,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 135,
    "country_id"=> 135,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 136,
    "country_id"=> 136,
    "name"=> "British Pound Sterling",
    "code"=> "GBP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 137,
    "country_id"=> 137,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 138,
    "country_id"=> 138,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 139,
    "country_id"=> 139,
    "name"=> "MRO",
    "code"=> "MRO",
    "precision"=> 2,
    "symbol"=> "MRU",
    "symbol_native"=> "MRU",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 140,
    "country_id"=> 140,
    "name"=> "Mauritian Rupee",
    "code"=> "MUR",
    "precision"=> 0,
    "symbol"=> "MURs",
    "symbol_native"=> "MURs",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 141,
    "country_id"=> 141,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 142,
    "country_id"=> 142,
    "name"=> "Mexican Peso",
    "code"=> "MXN",
    "precision"=> 2,
    "symbol"=> "MX$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 143,
    "country_id"=> 143,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 144,
    "country_id"=> 144,
    "name"=> "Moldovan Leu",
    "code"=> "MDL",
    "precision"=> 2,
    "symbol"=> "MDL",
    "symbol_native"=> "MDL",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 145,
    "country_id"=> 145,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 146,
    "country_id"=> 146,
    "name"=> "MNT",
    "code"=> "MNT",
    "precision"=> 2,
    "symbol"=> "₮",
    "symbol_native"=> "₮",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 147,
    "country_id"=> 147,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 148,
    "country_id"=> 148,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 149,
    "country_id"=> 149,
    "name"=> "Moroccan Dirham",
    "code"=> "MAD",
    "precision"=> 2,
    "symbol"=> "MAD",
    "symbol_native"=> "د.م.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 150,
    "country_id"=> 150,
    "name"=> "Mozambican Metical",
    "code"=> "MZN",
    "precision"=> 2,
    "symbol"=> "MTn",
    "symbol_native"=> "MTn",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 151,
    "country_id"=> 151,
    "name"=> "Myanma Kyat",
    "code"=> "MMK",
    "precision"=> 0,
    "symbol"=> "MMK",
    "symbol_native"=> "K",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 152,
    "country_id"=> 152,
    "name"=> "Namibian Dollar",
    "code"=> "NAD",
    "precision"=> 2,
    "symbol"=> "N$",
    "symbol_native"=> "N$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 153,
    "country_id"=> 153,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 154,
    "country_id"=> 154,
    "name"=> "Nepalese Rupee",
    "code"=> "NPR",
    "precision"=> 2,
    "symbol"=> "NPRs",
    "symbol_native"=> "नेरू",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 155,
    "country_id"=> 155,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 156,
    "country_id"=> 156,
    "name"=> "XPF",
    "code"=> "XPF",
    "precision"=> 2,
    "symbol"=> "₣",
    "symbol_native"=> "₣",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 157,
    "country_id"=> 157,
    "name"=> "New Zealand Dollar",
    "code"=> "NZD",
    "precision"=> 2,
    "symbol"=> "NZ$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 158,
    "country_id"=> 158,
    "name"=> "Nicaraguan Córdoba",
    "code"=> "NIO",
    "precision"=> 2,
    "symbol"=> "C$",
    "symbol_native"=> "C$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 159,
    "country_id"=> 159,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 160,
    "country_id"=> 160,
    "name"=> "Nigerian Naira",
    "code"=> "NGN",
    "precision"=> 2,
    "symbol"=> "₦",
    "symbol_native"=> "₦",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 161,
    "country_id"=> 161,
    "name"=> "New Zealand Dollar",
    "code"=> "NZD",
    "precision"=> 2,
    "symbol"=> "NZ$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 162,
    "country_id"=> 162,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 163,
    "country_id"=> 163,
    "name"=> "KPW",
    "code"=> "KPW",
    "precision"=> 2,
    "symbol"=> "₩",
    "symbol_native"=> "₩",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 164,
    "country_id"=> 164,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 165,
    "country_id"=> 165,
    "name"=> "Norwegian Krone",
    "code"=> "NOK",
    "precision"=> 2,
    "symbol"=> "Nkr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 166,
    "country_id"=> 166,
    "name"=> "Omani Rial",
    "code"=> "OMR",
    "precision"=> 3,
    "symbol"=> "OMR",
    "symbol_native"=> "ر.ع.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 167,
    "country_id"=> 167,
    "name"=> "Pakistani Rupee",
    "code"=> "PKR",
    "precision"=> 0,
    "symbol"=> "PKRs",
    "symbol_native"=> "₨",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 168,
    "country_id"=> 168,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 169,
    "country_id"=> 169,
    "name"=> "Israeli New Sheqel",
    "code"=> "ILS",
    "precision"=> 2,
    "symbol"=> "₪",
    "symbol_native"=> "₪",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 170,
    "country_id"=> 170,
    "name"=> "Panamanian Balboa",
    "code"=> "PAB",
    "precision"=> 2,
    "symbol"=> "B/.",
    "symbol_native"=> "B/.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 171,
    "country_id"=> 171,
    "name"=> "PGK",
    "code"=> "PGK",
    "precision"=> 2,
    "symbol"=> "K",
    "symbol_native"=> "K",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 172,
    "country_id"=> 172,
    "name"=> "Paraguayan Guarani",
    "code"=> "PYG",
    "precision"=> 0,
    "symbol"=> "₲",
    "symbol_native"=> "₲",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 173,
    "country_id"=> 173,
    "name"=> "Peruvian Nuevo Sol",
    "code"=> "PEN",
    "precision"=> 2,
    "symbol"=> "S/.",
    "symbol_native"=> "S/.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 174,
    "country_id"=> 174,
    "name"=> "Philippine Peso",
    "code"=> "PHP",
    "precision"=> 2,
    "symbol"=> "₱",
    "symbol_native"=> "₱",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 175,
    "country_id"=> 175,
    "name"=> "New Zealand Dollar",
    "code"=> "NZD",
    "precision"=> 2,
    "symbol"=> "NZ$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 176,
    "country_id"=> 176,
    "name"=> "Polish Zloty",
    "code"=> "PLN",
    "precision"=> 2,
    "symbol"=> "zł",
    "symbol_native"=> "zł",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 177,
    "country_id"=> 177,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 178,
    "country_id"=> 178,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 179,
    "country_id"=> 179,
    "name"=> "Qatari Rial",
    "code"=> "QAR",
    "precision"=> 2,
    "symbol"=> "QR",
    "symbol_native"=> "ر.ق.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 180,
    "country_id"=> 180,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 181,
    "country_id"=> 181,
    "name"=> "Romanian Leu",
    "code"=> "RON",
    "precision"=> 2,
    "symbol"=> "RON",
    "symbol_native"=> "RON",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 182,
    "country_id"=> 182,
    "name"=> "Russian Ruble",
    "code"=> "RUB",
    "precision"=> 2,
    "symbol"=> "RUB",
    "symbol_native"=> "₽.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 183,
    "country_id"=> 183,
    "name"=> "Rwandan Franc",
    "code"=> "RWF",
    "precision"=> 0,
    "symbol"=> "RWF",
    "symbol_native"=> "FR",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 184,
    "country_id"=> 184,
    "name"=> "SHP",
    "code"=> "SHP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 185,
    "country_id"=> 185,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 186,
    "country_id"=> 186,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 187,
    "country_id"=> 187,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 188,
    "country_id"=> 188,
    "name"=> "XCD",
    "code"=> "XCD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 189,
    "country_id"=> 189,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 190,
    "country_id"=> 190,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 191,
    "country_id"=> 191,
    "name"=> "WST",
    "code"=> "WST",
    "precision"=> 2,
    "symbol"=> "SAT",
    "symbol_native"=> "SAT",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 192,
    "country_id"=> 192,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 193,
    "country_id"=> 193,
    "name"=> "STD",
    "code"=> "STD",
    "precision"=> 2,
    "symbol"=> "Db",
    "symbol_native"=> "Db",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 194,
    "country_id"=> 194,
    "name"=> "Saudi Riyal",
    "code"=> "SAR",
    "precision"=> 2,
    "symbol"=> "SR",
    "symbol_native"=> "ر.س.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 195,
    "country_id"=> 195,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 196,
    "country_id"=> 196,
    "name"=> "Serbian Dinar",
    "code"=> "RSD",
    "precision"=> 0,
    "symbol"=> "din.",
    "symbol_native"=> "дин.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 197,
    "country_id"=> 197,
    "name"=> "SCR",
    "code"=> "SCR",
    "precision"=> 2,
    "symbol"=> "SRe",
    "symbol_native"=> "SRe",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 198,
    "country_id"=> 198,
    "name"=> "SLL",
    "code"=> "SLL",
    "precision"=> 2,
    "symbol"=> "Le",
    "symbol_native"=> "Le",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 199,
    "country_id"=> 199,
    "name"=> "Singapore Dollar",
    "code"=> "SGD",
    "precision"=> 2,
    "symbol"=> "S$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 200,
    "country_id"=> 200,
    "name"=> "ANG",
    "code"=> "ANG",
    "precision"=> 2,
    "symbol"=> "ƒ",
    "symbol_native"=> "ƒ",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 201,
    "country_id"=> 201,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 202,
    "country_id"=> 202,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 203,
    "country_id"=> 203,
    "name"=> "SBD",
    "code"=> "SBD",
    "precision"=> 2,
    "symbol"=> "Si$",
    "symbol_native"=> "Si$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 204,
    "country_id"=> 204,
    "name"=> "Somali Shilling",
    "code"=> "SOS",
    "precision"=> 0,
    "symbol"=> "Ssh",
    "symbol_native"=> "Ssh",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 205,
    "country_id"=> 205,
    "name"=> "South African Rand",
    "code"=> "ZAR",
    "precision"=> 2,
    "symbol"=> "R",
    "symbol_native"=> "R",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 206,
    "country_id"=> 206,
    "name"=> "British Pound Sterling",
    "code"=> "GBP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 207,
    "country_id"=> 207,
    "name"=> "South Korean Won",
    "code"=> "KRW",
    "precision"=> 0,
    "symbol"=> "₩",
    "symbol_native"=> "₩",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 208,
    "country_id"=> 208,
    "name"=> "SSP",
    "code"=> "SSP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 209,
    "country_id"=> 209,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 210,
    "country_id"=> 210,
    "name"=> "Sri Lankan Rupee",
    "code"=> "LKR",
    "precision"=> 2,
    "symbol"=> "SLRs",
    "symbol_native"=> "SL Re",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 211,
    "country_id"=> 211,
    "name"=> "Sudanese Pound",
    "code"=> "SDG",
    "precision"=> 2,
    "symbol"=> "SDG",
    "symbol_native"=> "SDG",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 212,
    "country_id"=> 212,
    "name"=> "SRD",
    "code"=> "SRD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 213,
    "country_id"=> 213,
    "name"=> "Norwegian Krone",
    "code"=> "NOK",
    "precision"=> 2,
    "symbol"=> "Nkr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 214,
    "country_id"=> 214,
    "name"=> "SZL",
    "code"=> "SZL",
    "precision"=> 2,
    "symbol"=> "E",
    "symbol_native"=> "E",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 215,
    "country_id"=> 215,
    "name"=> "Swedish Krona",
    "code"=> "SEK",
    "precision"=> 2,
    "symbol"=> "Skr",
    "symbol_native"=> "kr",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 216,
    "country_id"=> 216,
    "name"=> "Swiss Franc",
    "code"=> "CHF",
    "precision"=> 2,
    "symbol"=> "CHF",
    "symbol_native"=> "CHF",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 217,
    "country_id"=> 217,
    "name"=> "Syrian Pound",
    "code"=> "SYP",
    "precision"=> 0,
    "symbol"=> "SY£",
    "symbol_native"=> "ل.س.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 218,
    "country_id"=> 218,
    "name"=> "New Taiwan Dollar",
    "code"=> "TWD",
    "precision"=> 2,
    "symbol"=> "NT$",
    "symbol_native"=> "NT$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 219,
    "country_id"=> 219,
    "name"=> "TJS",
    "code"=> "TJS",
    "precision"=> 2,
    "symbol"=> "SM",
    "symbol_native"=> "SM",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 220,
    "country_id"=> 220,
    "name"=> "Tanzanian Shilling",
    "code"=> "TZS",
    "precision"=> 0,
    "symbol"=> "TSh",
    "symbol_native"=> "TSh",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 221,
    "country_id"=> 221,
    "name"=> "Thai Baht",
    "code"=> "THB",
    "precision"=> 2,
    "symbol"=> "฿",
    "symbol_native"=> "฿",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 222,
    "country_id"=> 222,
    "name"=> "BSD",
    "code"=> "BSD",
    "precision"=> 2,
    "symbol"=> "B$",
    "symbol_native"=> "B$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 223,
    "country_id"=> 223,
    "name"=> "CFA Franc BCEAO",
    "code"=> "XOF",
    "precision"=> 0,
    "symbol"=> "CFA",
    "symbol_native"=> "CFA",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 224,
    "country_id"=> 224,
    "name"=> "New Zealand Dollar",
    "code"=> "NZD",
    "precision"=> 2,
    "symbol"=> "NZ$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 225,
    "country_id"=> 225,
    "name"=> "Tongan Paʻanga",
    "code"=> "TOP",
    "precision"=> 2,
    "symbol"=> "T$",
    "symbol_native"=> "T$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 226,
    "country_id"=> 226,
    "name"=> "Trinidad and Tobago Dollar",
    "code"=> "TTD",
    "precision"=> 2,
    "symbol"=> "TT$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 227,
    "country_id"=> 227,
    "name"=> "Tunisian Dinar",
    "code"=> "TND",
    "precision"=> 3,
    "symbol"=> "DT",
    "symbol_native"=> "د.ت.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 228,
    "country_id"=> 228,
    "name"=> "Turkish Lira",
    "code"=> "TRY",
    "precision"=> 2,
    "symbol"=> "TL",
    "symbol_native"=> "₺",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 229,
    "country_id"=> 229,
    "name"=> "TMT",
    "code"=> "TMT",
    "precision"=> 2,
    "symbol"=> "T",
    "symbol_native"=> "T",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 230,
    "country_id"=> 230,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 231,
    "country_id"=> 231,
    "name"=> "Australian Dollar",
    "code"=> "AUD",
    "precision"=> 2,
    "symbol"=> "AU$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 232,
    "country_id"=> 232,
    "name"=> "Ugandan Shilling",
    "code"=> "UGX",
    "precision"=> 0,
    "symbol"=> "USh",
    "symbol_native"=> "USh",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 233,
    "country_id"=> 233,
    "name"=> "Ukrainian Hryvnia",
    "code"=> "UAH",
    "precision"=> 2,
    "symbol"=> "₴",
    "symbol_native"=> "₴",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 234,
    "country_id"=> 234,
    "name"=> "United Arab Emirates Dirham",
    "code"=> "AED",
    "precision"=> 2,
    "symbol"=> "AED",
    "symbol_native"=> "د.إ.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 235,
    "country_id"=> 235,
    "name"=> "British Pound Sterling",
    "code"=> "GBP",
    "precision"=> 2,
    "symbol"=> "£",
    "symbol_native"=> "£",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 236,
    "country_id"=> 236,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 237,
    "country_id"=> 237,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 238,
    "country_id"=> 238,
    "name"=> "Uruguayan Peso",
    "code"=> "UYU",
    "precision"=> 2,
    "symbol"=> "$U",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 239,
    "country_id"=> 239,
    "name"=> "Uzbekistan Som",
    "code"=> "UZS",
    "precision"=> 0,
    "symbol"=> "UZS",
    "symbol_native"=> "UZS",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 240,
    "country_id"=> 240,
    "name"=> "VUV",
    "code"=> "VUV",
    "precision"=> 2,
    "symbol"=> "VT",
    "symbol_native"=> "VT",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 241,
    "country_id"=> 241,
    "name"=> "Euro",
    "code"=> "EUR",
    "precision"=> 2,
    "symbol"=> "€",
    "symbol_native"=> "€",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 242,
    "country_id"=> 242,
    "name"=> "Venezuelan Bolívar",
    "code"=> "VEF",
    "precision"=> 2,
    "symbol"=> "Bs.F.",
    "symbol_native"=> "Bs.F.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 243,
    "country_id"=> 243,
    "name"=> "Vietnamese Dong",
    "code"=> "VND",
    "precision"=> 0,
    "symbol"=> "₫",
    "symbol_native"=> "₫",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 244,
    "country_id"=> 244,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 245,
    "country_id"=> 245,
    "name"=> "US Dollar",
    "code"=> "USD",
    "precision"=> 2,
    "symbol"=> "$",
    "symbol_native"=> "$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 246,
    "country_id"=> 246,
    "name"=> "XPF",
    "code"=> "XPF",
    "precision"=> 2,
    "symbol"=> "₣",
    "symbol_native"=> "₣",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 247,
    "country_id"=> 247,
    "name"=> "Moroccan Dirham",
    "code"=> "MAD",
    "precision"=> 2,
    "symbol"=> "MAD",
    "symbol_native"=> "د.م.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 248,
    "country_id"=> 248,
    "name"=> "Yemeni Rial",
    "code"=> "YER",
    "precision"=> 0,
    "symbol"=> "YR",
    "symbol_native"=> "ر.ي.",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 249,
    "country_id"=> 249,
    "name"=> "ZMW",
    "code"=> "ZMW",
    "precision"=> 2,
    "symbol"=> "ZK",
    "symbol_native"=> "ZK",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
],
  [
    "id"=> 250,
    "country_id"=> 250,
    "name"=> "Zimbabwean Dollar",
    "code"=> "ZWL",
    "precision"=> 0,
    "symbol"=> "ZWL$",
    "symbol_native"=> "ZWL$",
    "symbol_first"=> 1,
    "decimal_mark"=> ".",
    "thousands_separator"=> ","
]
        ]);
    }
}
